### PR TITLE
Add support for networks configuration

### PR DESCRIPTION
**Pull request by simoncaron**
Added a few lines to support [the networks and networks aliases](https://docs.docker.com/compose/compose-file/compose-file-v2/#networks) configurations.

### CODE REVIEW

**Comment by itsmegb** [comment]
One suggestion i have for this (that I used locally) is to rename the 'networks' variable to something like 'docker_networks'. This would make it clearer in the ansible config that the defined variables are for docker specifically and not for anything else.

**Comment by coredotbin** [comment]
> rename the 'networks' variable to something like 'docker_networks'

@itsmegb : I would agree, but under this train of thought, we may also propose to change the `containers` variable to `docker_containers` This would be a breaking change, but I'd assume we'd want to create and stick with a standard.

This would be a question for @ironicbadger

**Comment by SolidRhino** [comment]
Why isn't this merged? This is one of the options that are missing. @ironicbadger

**Comment by ironicbadger** [comment]
> Why isn't this merged? This is one of the options that are missing. @ironicbadger

life.

> > rename the 'networks' variable to something like 'docker_networks'
> 
> @itsmegb : I would agree, but under this train of thought, we may also propose to change the `containers` variable to `docker_containers` This would be a breaking change, but I'd assume we'd want to create and stick with a standard.
> 
> This would be a question for @ironicbadger

Renaming to `docker_networks` would be preferable so that it's clearer from the Ansible side I quite agree.

**Comment by itsmegb** [comment]
Those changes make sense, but there will nee to be another PR as its
already been merged 😀

I've switched to using Jinja templates because of the complexity of my
setup, so I'm not using this modification anymore.

**Comment by simoncaron** [comment]
You can take all the time you want to review my PRs @ironicbadger... as long as you keep entertaining me with a new episode of Self-Hosted every two week ;)

I renamed the variable to `docker_networks`.

**Comment by ironicbadger** [comment]
Thanks for the changes. I think an example for the readme might be useful too, then I'll merge.

**Comment by seedzero** [comment]
@simoncaron @ironicbadger I've started using this PR in my infrastructure. Example for the readme should be something like:
 ```docker_networks:
  - network_name: proxy_private
    active: true
    external: false```

**Comment by BCNelson** [comment]
Adding the option for [internal](https://docs.docker.com/compose/compose-file/06-networks/#internal)  would be very helpful this is what it looks like in docker compose
```
network:
  internal_only_network:
    internal: true
```
@simoncaron Let me know if you would like a PR to your branch

**Comment by ironicbadger** [comment]
picking this up again (sorry i let it sit so long). i'm a bit confused as to the current state of what's here.

**Comment by ironicbadger** [comment]
Still want to add this but it's too old and stale. Likely the OG poster moved on. If you see this and want to reopen, please do.

**Pull request closed without merging**
