### PR TITLE
Add cap_drop and read_only

### PR DESCRIPTION
**Pull request by FuzzyMistborn**
Needed for Invidious (https://docs.invidious.io/installation/#docker-compose-method-production)

### CODE REVIEW

**Review by ironicbadger — APPROVED** [review]

**Comment by ironicbadger** [comment]
Can you resolve the conflicts fuzzy?

**Comment by FuzzyMistborn** [comment]
Looks like you undid what I did in #33 in #34.  I'm going to close this one and open a new.  I also noticed recently there's now two `deploy/resources` sections that need to be fixed.  I'll work on that later today.

**Comment by ironicbadger** [comment]
I'm wondering how much more I can be bothered to bolt onto this role instead of a new tool that takes in existing compose yaml files instead.

**Comment by FuzzyMistborn** [comment]
Interesting idea. https://github.com/caddy-ansible/caddy-ansible does something where you can do the entire config file in a variable or template file.

**Pull request closed without merging**
